"""
B3 Price Lookup API
FastAPI backend that queries the SQLite database generated by parser_notebook.ipynb

Endpoints:
    GET /prices?tickers=MXRF11,HGLG11&date=2026-03-31
    GET /tickers
    GET /dates/available?ticker=MXRF11
"""

from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
import sqlite3
import os
import re
from pathlib import Path
from datetime import datetime

# ---------------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------------
DB_PATH = os.getenv("DB_PATH", "data/b3.db")

# ---------------------------------------------------------------------------
# RATE LIMITER
# ---------------------------------------------------------------------------
limiter = Limiter(key_func=get_remote_address, default_limits=["60/minute"])

app = FastAPI(
    title="B3 Price Lookup API",
    description="Closing prices for B3 stocks and FIIs",
    version="1.0.0",
)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# Allow requests from any origin (needed for the webpage to call this API)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# DB helper
# ---------------------------------------------------------------------------
def get_conn() -> sqlite3.Connection:
    db = Path(DB_PATH)
    if not db.exists():
        raise HTTPException(status_code=503, detail=f"Database not found at {DB_PATH}")
    conn = sqlite3.connect(db)
    conn.row_factory = sqlite3.Row
    return conn


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------
TICKER_RE = re.compile(r'^[A-Z0-9]{1,12}$')
DATE_RE   = re.compile(r'^[0-9]{4}-[0-9]{2}-[0-9]{2}$')

def validate_tickers(raw: str) -> list[str]:
    tickers = [t.strip().upper() for t in raw.split(",") if t.strip()]
    if not tickers:
        raise HTTPException(status_code=400, detail="Nenhum ativo informado.")
    if len(tickers) > 50:
        raise HTTPException(status_code=400, detail="Máximo de 50 ativos por consulta.")
    for t in tickers:
        if not TICKER_RE.match(t):
            raise HTTPException(status_code=400, detail=f"Ativo inválido: '{t}'. Use apenas letras e números (máx. 12 caracteres).")
    return tickers

def validate_date(date: str) -> str:
    if not DATE_RE.match(date):
        raise HTTPException(status_code=400, detail="Data inválida. Use o formato YYYY-MM-DD.")
    try:
        datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        raise HTTPException(status_code=400, detail=f"Data inválida: '{date}'.")
    return date

# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/")
def root():
    return {"status": "ok", "message": "B3 Price Lookup API is running"}


@app.get("/prices")
@limiter.limit("30/minute")
def get_prices(
    request: Request,
    tickers: str = Query(..., description="Comma-separated list of tickers, e.g. MXRF11,HGLG11"),
    date: str = Query(..., description="Date in YYYY-MM-DD format, e.g. 2026-03-31"),
):
    """
    Returns closing price and volume for each requested ticker on the given date.
    If a ticker had no trade on that date, it is returned with null values.
    """
    ticker_list = validate_tickers(tickers)
    validate_date(date)

    placeholders = ",".join("?" * len(ticker_list))
    query = f"""
        SELECT
            CodNeg      AS ticker,
            DtPregao    AS date,
            PrecoAbertura AS open,
            PrecoMaximo   AS high,
            PrecoMinimo   AS low,
            PrecoUltimo   AS close,
            VolNegocios   AS volume,
            NumNegocios   AS trades
        FROM cotahist
        WHERE CodNeg IN ({placeholders})
          AND DtPregao = ?
        ORDER BY CodNeg
    """

    conn = get_conn()
    rows = conn.execute(query, ticker_list + [date]).fetchall()
    conn.close()

    # Build result — include nulls for tickers with no data on that date
    found = {row["ticker"]: dict(row) for row in rows}
    results = []
    for ticker in ticker_list:
        if ticker in found:
            results.append(found[ticker])
        else:
            results.append({
                "ticker": ticker,
                "date": date,
                "open": None,
                "high": None,
                "low": None,
                "close": None,
                "volume": None,
                "trades": None,
                "note": "No data for this ticker on this date"
            })

    return {"date": date, "results": results}


@app.get("/tickers")
@limiter.limit("20/minute")
def get_tickers(request: Request, search: str = Query(None, description="Optional search filter, e.g. 'MXRF'")):
    """
    Returns all unique tickers in the database.
    Optionally filter by partial name with ?search=XYZ
    """
    conn = get_conn()

    if search:
        if len(search) > 12 or not re.match(r'^[A-Z0-9]+$', search.upper()):
            raise HTTPException(status_code=400, detail="Filtro de busca inválido.")
        rows = conn.execute(
            "SELECT DISTINCT CodNeg AS ticker, NomResumido AS name FROM cotahist WHERE CodNeg LIKE ? ORDER BY CodNeg",
            (f"%{search.upper()}%",)
        ).fetchall()
    else:
        rows = conn.execute(
            "SELECT DISTINCT CodNeg AS ticker, NomResumido AS name FROM cotahist ORDER BY CodNeg"
        ).fetchall()

    conn.close()
    return {"count": len(rows), "tickers": [dict(r) for r in rows]}


@app.get("/dates/all")
def get_all_dates():
    """
    Returns all unique trading dates in the entire database.
    Called once on page load to restrict the date picker.
    """
    conn = get_conn()
    rows = conn.execute(
        "SELECT DISTINCT DtPregao AS date FROM cotahist ORDER BY DtPregao DESC"
    ).fetchall()
    conn.close()

    dates = [r["date"] for r in rows]
    return {
        "count": len(dates),
        "latest": dates[0] if dates else None,
        "earliest": dates[-1] if dates else None,
        "dates": dates,
    }


@app.get("/dates/available")
def get_available_dates(
    ticker: str = Query(..., description="Ticker to check, e.g. MXRF11")
):
    """
    Returns all trading dates available in the DB for a given ticker.
    Useful for disabling unavailable dates in the date picker.
    """
    conn = get_conn()
    rows = conn.execute(
        "SELECT DISTINCT DtPregao AS date FROM cotahist WHERE CodNeg = ? ORDER BY DtPregao DESC",
        (ticker.upper(),)
    ).fetchall()
    conn.close()

    if not rows:
        raise HTTPException(status_code=404, detail=f"Ticker {ticker.upper()} not found")

    dates = [r["date"] for r in rows]
    return {
        "ticker": ticker.upper(),
        "count": len(dates),
        "latest": dates[0],
        "earliest": dates[-1],
        "dates": dates,
    }
